import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';
import 'package:archespace_mobile/core/crypto/arche_crypto.dart';

/// The go/no-go gate for the mobile port: prove the Dart crypto reproduces and
/// consumes the exact bytes the web produces. Vectors are vendored from the web
/// repo (`spec/vectors.json`, generated by `scripts/gen-crypto-vectors.mjs`).
void main() {
  final vectors = jsonDecode(File('spec/vectors.json').readAsStringSync())
      as Map<String, dynamic>;

  test('derives the expected key for every KDF vector', () async {
    for (final v in vectors['kdf'] as List) {
      final key = await ArcheCrypto.deriveVaultKey(v['secret'], v['descriptor']);
      expect(base64.encode(key), v['expectedKeyB64'],
          reason: '${v['algo']} / ${v['secret']}');
    }
  });

  test('decrypts every symmetric vector', () async {
    for (final v in vectors['decrypt'] as List) {
      final key = base64.decode(v['keyB64']);
      expect(await ArcheCrypto.decryptArc1(v['arc1'], key), v['expectedPlaintext']);
    }
  });

  test('runs the full vault-unlock flow', () async {
    final vu = vectors['vaultUnlock'] as Map<String, dynamic>;
    final pinKey = await ArcheCrypto.deriveVaultKey(vu['pin'], vu['salt']);
    final rawB64 = await ArcheCrypto.decryptArc1(vu['wrappedKey'], pinKey);
    final masterKey = base64.decode(rawB64);

    expect(await ArcheCrypto.decryptArc1(vu['keyCheck'], masterKey),
        vu['checkPlaintext']);
    for (final s in vu['samples'] as List) {
      expect(await ArcheCrypto.decryptArc1(s['arc1'], masterKey), s['plaintext']);
    }
  });

  test('encrypt then decrypt round-trips (and web can read it in principle)',
      () async {
    final key = base64.decode((vectors['decrypt'] as List).first['keyB64']);
    const message = 'round trip: héllo 🔐 你好';
    final arc1 = await ArcheCrypto.encryptArc1(message, key);
    expect(arc1.startsWith('arc1:'), isTrue);
    expect(await ArcheCrypto.decryptArc1(arc1, key), message);
  });
}
